name: Dependabot Auto-Merge

on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'  # Only run for Dependabot PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto-Merge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
          target: minor  # Allows patch & minor updates to be auto-merged
